server:
  port: 9999

spring:
  profiles:
    active: dev

---
spring:
  profiles: local
  datasource:
    username: newbie
    password: newbie!
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mysql://218.38.15.94:3306/NEWBIE

---
spring:
  profiles: dev
  datasource:
    username: newbie
    password: newbie!
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mysql://218.38.15.94:3306/NEWBIE
  servlet:    multipart:      max-file-size: 10MB
      max-request-size: 10MB        